// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyvi_DDSU0TeZOuaONVXuDqd_GIXEzw8',
    appId: '1:316753391709:web:ecb77f62e869e21a641db4',
    messagingSenderId: '316753391709',
    projectId: 'whathero-73605',
    authDomain: 'whathero-73605.firebaseapp.com',
    storageBucket: 'whathero-73605.firebasestorage.app',
    measurementId: 'G-88TYGL0JHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYKH1NS-cOHEHhDGOMyR-jRnT-tVGHDQ',
    appId: '1:316753391709:android:5b7b3b6257fa6727641db4',
    messagingSenderId: '316753391709',
    projectId: 'whathero-73605',
    storageBucket: 'whathero-73605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Bq1DjhhOl-WkkHLoG0ecA_wOxH8dXZY',
    appId: '1:316753391709:ios:cc1f9b4cad48d9a5641db4',
    messagingSenderId: '316753391709',
    projectId: 'whathero-73605',
    storageBucket: 'whathero-73605.firebasestorage.app',
    iosBundleId: 'com.sintaxis.whathero',
  );

}